chore: release `--debug` from `goreleaser`
It seems it no longer recognized
Ref: https://github.com/ashishb/wp2hugo/actions/runs/9735144099/job/26864012080

```
/opt/hostedtoolcache/goreleaser-action/2.0.1/x64/goreleaser release --clean --debug
  ⨯ command failed                                   error=unknown flag: --debug
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.0.1/x64/goreleaser' failed with exit code 1
```